### ISSUE TITLE
Support `nth-child(x)`

### ISSUE THREAD

**Issue by Iiridayn** [calebsander/html-soup#3]
Sadly, one of the sites has an element which I unfortunately need to target with `#page-submission table table table tr:nth-child(2)`. As such, I'd appreciate support for `nth-child` as well :). I might have to dig in to fix it, though I'm not familiar with Typescript (had a bad experience, dug into the philosophy, realized it didn't give runtime checks, and moved on with life).

**Comment by Iiridayn** [comment]
I might also be able to get by with renaming `parent` to `parentElement` and use `#page-submission table table table tr a img` and back out two levels. It'd have to be named to match the browser though. I'll probably use that as a workaround for now, since I'm targeting two platforms at the same time :).

**Comment by calebsander** [comment]
Sure, I'll implement `nth-child`, `nth-last-child`, `nth-of-type`, and `nth-last-of-type`. I'm not going to rename `parent`, though, since `html-soup` is not meant to implement the DOM API and I have several libraries that depend on its current interface.

**Comment by Iiridayn** [comment]
No worries - the css selectors support should be plenty w/o needing DOM style element navigation. Pretty impressed and happy with what I've seen of your code thus far - thank you for sharing :).

**Comment by Iiridayn** [comment]
I feel pretty silly - I could have worked around it using `#page-submission table table table tr + tr`. Clearly my CSS-fu is weak :|.
